#!/usr/bin/env bash
#this bash script prints "best School" 10 times using a for loop
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done